apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "vault.fullname" . }}-dev"
  labels:
    app: "{{ template "vault.name" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  VAULT_DEV_ROOT_TOKEN_ID: {{ .Values.vault.devRootToken }}
